export const ADD_CONSTANT_NODE = 'ADD_CONSTANT_NODE';
export const ADD_MODEL_NODE = 'ADD_MODEL_NODE';
export const ADD_CONNECTOR = 'ADD_CONNECTOR';
export const REMOVE_CONNECTOR = 'REMOVE_CONNECTOR';
export const REMOVE_NODE = 'REMOVE_NODE';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const FB_LOGIN_START = 'FB_LOGIN_START';
export const FB_LOGIN_SUCCESS = 'FB_LOGIN_SUCCESS';
export const FB_LOGIN_FAIL = 'FB_LOGIN_FAIL';
export const FB_LOGOUT = 'FB_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
export const NOTIFICATION_NEXT = 'NOTIFICATION_NEXT'
export const NOTIFICATION_CLOSE = 'NOTIFICATION_CLOSE'
export const NOTIFICATION_SHIFT_QUEUE = 'NOTIFICATION_SHIFT_QUEUE'


export const SPINNER_START = 'SPINNER_START';
export const SPINNER_STOP = 'SPINNER_STOP';

export const APP_VALUES_GET_ROLES = 'APP_VALUES_GET_ROLES';
export const APP_VALUES_GET_ROLES_COMPLETE = 'APP_VALUES_GET_ROLES_COMPLETE';

export const APP_VALUES_GET_DATA_TYPES = 'APP_VALUES_GET_DATA_TYPES';
export const APP_VALUES_GET_DATA_TYPES_COMPLETE = 'APP_VALUES_GET_DATA_TYPES_COMPLETE';

export const USER_SAVE = 'USER_SAVE';
export const USER_SUSPEND = 'USER_SUSPEND';
export const USER_DELETE = 'USER_DELETE';
export const USER_SETTINGS_UPDATE_SUCCESS = 'USER_SETTINGS_UPDATE_SUCCESS';

export const PROJECT_LOADED = 'PROJECT_LOADED';
export const PROJECT_UNLOADED = 'PROJECT_UNLOADED';